--INSERT INTO "PREPAS".usuario VALUES ('smaf@usb.ve','12345','','Steph','Alib','','','','f','S','S','28','S','36','true','administrador');
INSERT INTO "PREPAS".usuario VALUES ('mgomez@usb.ve','dsiusb','','Marcos','Gómez','','','','f','S','S','28','S','36','true','administrador');
--INSERT INTO "PREPAS".usuario VALUES ('sofia@usb.ve','12345','','sofia','Soto','','','','f','S','S','28','S','36','true','usuario');
--INSERT INTO "PREPAS".usuario VALUES ('astrid@usb.ve','12345','','astrid','Soto','','','','f','S','S','28','S','36','true','usuario');
INSERT INTO "PREPAS".noticia VALUES ('mgomez@usb.ve','Entrega 30%','Ya se encuentra habilitado el sistema para la DSI con el 30% de los casos de uso implementados. ','2012-11-29');

INSERT INTO "PREPAS".equipo VALUES ('cascoSeguridad','assets/materiales/c1.png','cabeza','Casco de Seguridad');
INSERT INTO "PREPAS".equipo VALUES ('cascoMotorizado','assets/materiales/c3.png','cabeza', 'Casco de motorizado');
INSERT INTO "PREPAS".equipo VALUES ('lentesCopa','assets/materiales/img.png','cabeza','Lentes de copa');
INSERT INTO "PREPAS".equipo VALUES ('lentesSeguridad','assets/materiales/img.png','cabeza','Lentes de seguridad');
INSERT INTO "PREPAS".equipo VALUES ('respiradorCaraCompleta','assets/materiales/img.png','cabeza', 'Respirador de cara completa');
INSERT INTO "PREPAS".equipo VALUES ('respiradorMedioRostro','assets/materiales/img.png','cabeza','Respirador de medio rostro');
INSERT INTO "PREPAS".equipo VALUES ('mascarilla','assets/materiales/img.png','cabeza','Mascarilla');
INSERT INTO "PREPAS".equipo VALUES ('gorro','assets/materiales/img.png','cabeza','Gorro');
INSERT INTO "PREPAS".equipo VALUES ('caretaSoldar','assets/materiales/img.png','cabeza','Cartea para soldar');
INSERT INTO "PREPAS".equipo VALUES ('gorraAzul','assets/materiales/img.png','cabeza','Gorra azul');
INSERT INTO "PREPAS".equipo VALUES ('gorraGrisLogo','assets/materiales/img.png','cabeza','Gorro gris logo USB');
INSERT INTO "PREPAS".equipo VALUES ('sombreroTipoPava','assets/materiales/img.png','cabeza','Sombrero tipo pava');
INSERT INTO "PREPAS".equipo VALUES ('botasDielectricas','assets/materiales/img.png','zapato','Botas dielectricas');
INSERT INTO "PREPAS".equipo VALUES ('botasPHierro','assets/materiales/img.png','zapato','Botas punta de hierro');
INSERT INTO "PREPAS".equipo VALUES ('botasCanaLarga','assets/materiales/img.png','zapato','Botas caña larga');
INSERT INTO "PREPAS".equipo VALUES ('botasTipoMilitar','assets/materiales/img.png','zapato','Botas tipo militar');
INSERT INTO "PREPAS".equipo VALUES ('botasVaquetaCanaLarga','assets/materiales/img.png','zapato','Botas vaqueta caña larga');
INSERT INTO "PREPAS".equipo VALUES ('botasMontanera','assets/materiales/img.png','zapato','Botas montañera');
INSERT INTO "PREPAS".equipo VALUES ('botasCueroVulcanizTactica','assets/materiales/img.png','zapato','Botas de cuero vulcanizadas');
INSERT INTO "PREPAS".equipo VALUES ('guantesCarnaza','assets/materiales/img.png','guantes','Guantes de carnaza');
INSERT INTO "PREPAS".equipo VALUES ('guantesCarnazaSoldador','assets/materiales/img.png','guantes','Guantes de carnaza soldador');
INSERT INTO "PREPAS".equipo VALUES ('guantesAntiAcido18','assets/materiales/img.png','guantes','Guantes antiacido 18');
INSERT INTO "PREPAS".equipo VALUES ('guantesLatex','assets/materiales/img.png','guantes','Guantes de latex');
INSERT INTO "PREPAS".equipo VALUES ('guantesKevlar14','assets/materiales/img.png','guantes', 'Guantes Kevlar 14');
INSERT INTO "PREPAS".equipo VALUES ('guantesKevlar20','assets/materiales/img.png','guantes','Guantes Kevlar 20');
INSERT INTO "PREPAS".equipo VALUES ('guantesVaqueta','assets/materiales/img.png','guantes','Guantes vaqueta');
INSERT INTO "PREPAS".equipo VALUES ('guantesNitrilo','assets/materiales/img.png','guantes','Guantes nitrilo');
INSERT INTO "PREPAS".equipo VALUES ('guantesMotorizado','assets/materiales/img.png','guantes','Guantes para motorizados');
INSERT INTO "PREPAS".equipo VALUES ('guantesAntideslizantes','assets/materiales/img.png','guantes','Guantes antideslizantes');
INSERT INTO "PREPAS".equipo VALUES ('guantesNeopreno','assets/materiales/img.png','guantes','Guantes de neopreno');
INSERT INTO "PREPAS".equipo VALUES ('filtroVaporOrganico','assets/materiales/img.png','cabeza','Filtro para vapor organico');
INSERT INTO "PREPAS".equipo VALUES ('filtroCloro','assets/materiales/img.png','cabeza','Filtro para cloro');
INSERT INTO "PREPAS".equipo VALUES ('filtroMercurio','assets/materiales/img.png','cabeza','Filtro para mercurio');
INSERT INTO "PREPAS".equipo VALUES ('arnesSeguridad','assets/materiales/img.png','pantalon','Arnés de seguridad');
INSERT INTO "PREPAS".equipo VALUES ('delantalCocinero','assets/materiales/img.png','camisa','Delantal de cocinero');
INSERT INTO "PREPAS".equipo VALUES ('delantalSoldadura','assets/materiales/img.png','camisa','Delantal para soldadura');
INSERT INTO "PREPAS".equipo VALUES ('delantalNeopreno','assets/materiales/img.png','camisa','Delantal de neopreno');
INSERT INTO "PREPAS".equipo VALUES ('delantalPVC','assets/materiales/img.png','camisa','Delantal PVC');
INSERT INTO "PREPAS".equipo VALUES ('calzadoAntideslizante','assets/materiales/img.png','zapato','Calzado antideslizante');
INSERT INTO "PREPAS".equipo VALUES ('chaquetaBombero','assets/materiales/img.png','camisa','Chaqueta bombero');
INSERT INTO "PREPAS".equipo VALUES ('pantalonTipoBombero','assets/materiales/img.png','pantalon','Pantalón tipo bombero');
INSERT INTO "PREPAS".equipo VALUES ('pantalonBomberoRescateAzul','assets/materiales/img.png','pantalon','Pantalón bombero rescate azul');
INSERT INTO "PREPAS".equipo VALUES ('uniformeTipoMilitar','assets/materiales/img.png','camisa','Uniforme tipo militar');
INSERT INTO "PREPAS".equipo VALUES ('botasCombateIncendio','assets/materiales/img.png','zapato','Botas combate contra contra incendio');
INSERT INTO "PREPAS".equipo VALUES ('guantesCombateIncendio','assets/materiales/img.png','guantes','Guantes combate incendio');
INSERT INTO "PREPAS".equipo VALUES ('impermeableMotorizado','assets/materiales/img.png','camisa','Impermeable motorizado');
INSERT INTO "PREPAS".equipo VALUES ('bragaGrisDobleCostura','assets/materiales/img.png','camisa','Braga gris doble costura');
INSERT INTO "PREPAS".equipo VALUES ('bragaNegraDobleCostura','assets/materiales/img.png','camisa','Braga negra doble costura');
INSERT INTO "PREPAS".equipo VALUES ('bataAzul','assets/materiales/img.png','camisa','Bata azul');
INSERT INTO "PREPAS".equipo VALUES ('bataGris','assets/materiales/img.png','camisa','Bata gris');
INSERT INTO "PREPAS".equipo VALUES ('bataNegra','assets/materiales/img.png','camisa','Bata negra');
INSERT INTO "PREPAS".equipo VALUES ('bataBlanca','assets/materiales/img.png','camisa','Bata blanca');
INSERT INTO "PREPAS".equipo VALUES ('chemisseAzul','assets/materiales/img.png','camisa','Chemisse azul');
INSERT INTO "PREPAS".equipo VALUES ('chemisseBeige','assets/materiales/img.png','camisa','Chemisse beige');
INSERT INTO "PREPAS".equipo VALUES ('chemisseVerde','assets/materiales/img.png','camisa','Chemisse verde');
INSERT INTO "PREPAS".equipo VALUES ('chemisseBlanca','assets/materiales/img.png','camisa','Chemisse blanca');
INSERT INTO "PREPAS".equipo VALUES ('chemisseGris','assets/materiales/img.png','camisa','Chemisse gris');
INSERT INTO "PREPAS".equipo VALUES ('blazerAzul','assets/materiales/img.png','camisa','Blazer azul');
INSERT INTO "PREPAS".equipo VALUES ('blueJeans','assets/materiales/img.png','pantalon','Blue jeans');
INSERT INTO "PREPAS".equipo VALUES ('camisaBlanca','assets/materiales/img.png','camisa','Camisa blanca');
INSERT INTO "PREPAS".equipo VALUES ('camisaAzul','assets/materiales/img.png','camisa','Camisa azul');
INSERT INTO "PREPAS".equipo VALUES ('camisaBeige','assets/materiales/img.png','camisa','Camisa beige');
INSERT INTO "PREPAS".equipo VALUES ('paraguas','assets/materiales/img.png','otros','Paraguas');
INSERT INTO "PREPAS".equipo VALUES ('pantallaAtalaje','assets/materiales/img.png','otros','Pantalla de atalaje');
INSERT INTO "PREPAS".equipo VALUES ('maletin','assets/materiales/img.png','otros','Maletín');
INSERT INTO "PREPAS".equipo VALUES ('camisaVestir','assets/materiales/img.png','camisa','Camisa de vestir');
INSERT INTO "PREPAS".equipo VALUES ('pantalonVestir','assets/materiales/img.png','pantalon','Pantalón de vestir');
INSERT INTO "PREPAS".equipo VALUES ('zapatoVestir','assets/materiales/img.png','zapato','Zapatos de vestir');
INSERT INTO "PREPAS".equipo VALUES ('chaquetaVestir','assets/materiales/img.png','camisa','Chaqueta de vestir');